[build-system]
requires = ["uv_build>=0.11.24,<0.12"]
build-backend = "uv_build"

[project]
name = "aws-sharepoint-connector"
version = "1.9.2"
description = "Provides a connector via Graph API between AWS and SharePoint"
authors = [
    { name = "Philip Sinfield"},
    { name = "Guy Wheeler"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13.14"
dependencies = [
    "azure-identity>=1.24.0",
    "boto3>=1.43.0",
    "pydantic-settings>=2.14.2",
    "pydantic>=2.12.3",
    "requests>=2.32.4",
]

[project.urls]
Repository = "https://github.com/ministryofjustice/aws-sharepoint-connector"

[dependency-groups]
dev = [
    "mypy>=2.2.0",
    "pre-commit>=4.0.0",
    "ruff>=0.16.0",
    "types-requests>=2.33.0.20260503",
]
package = [
    "packaging>=26.2",
    "python-semantic-release>=10.6.1",
    "toml-cli>=0.8.2",
    "typer>=0.26.8",
]
test = [
    "moto>=5.2.0",
    "pandas>=3.0.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.0.0",

]

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src", "."]

[tool.mypy]
strict = true
disallow_untyped_defs = true
exclude = "migrations|dist|build|typings"
explicit_package_bases = true
warn_unused_ignores = true
show_error_codes = true
mypy_path = "src"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov=src --cov=scripts --cov-report=term-missing --cov-report=xml"

[tool.ruff.lint]
select = ["ALL"]
# Remove warnings
ignore = [
    "CPY001", # Missing copyright notice
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "COM812", # Trailing comma missing
    "T201", # No print statements
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "ARG", # some arguments are unused in tests functions but useful (e.g. mocks)
    "PLR2004", # hardcoded test data is OK for tests
    "S101", # asserts are OK for tests
    "SLF001" # accessing private members is OK for tests
]

[tool.lint.ruff.pydocstyle]
convention = "google"

[tool.lint.ruff.isort]
known-first-party = ["src"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.lint.bandit]
skips = [
    "B101", # assert used
]

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = false
no_git_verify = false
tag_format = "v{version}"
add_partial_tags = false

[tool.semantic_release.branches.main]
match = "main"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.branches.other]
match = ".*"
prerelease_token = "rc"
prerelease = true

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[tool.semantic_release.changelog]
exclude_commit_patterns = []
mode = "update"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = true

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false
